name: cache purge

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/README.md'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: purge cache
              run: | 
                curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CF_ZONE_ID }}/purge_cache" \
                -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
                -H "Content-Type: application/json" \
                --data '{"purge_everything":true}'